### PR TITLE
Add LTI display name

### PR DESCRIPTION
**Pull request by RiteshChouhan21**
@dcadams please review, this PR will show lti display name for all the blocks.

### CODE REVIEW

**Review by dcadams — COMMENTED** [review]
The change looks good but you've re-ordered items and added an empty line so the change looks larger than it actually is. Can you fix this in both PR's so I see the minimum change.

Thanks.

**Comment by RiteshChouhan21** [comment]
@dcadams updated item's order now it's only one line change. 
The order was changed to differentiate Unit display name to LTI display name.

**Comment by dcadams** [comment]
I made these changes on my Tutor devstak and they look good.

:+1:

**Comment by RiteshChouhan21** [comment]
PR is squashed and merged into koa-tutor.

**Pull request merged**
